### ISSUE TITLE
how to draw point cloud with  depth result?

### ISSUE THREAD

**Issue by jinfagang** [TRI-ML/packnet-sfm#10]
Any scripts convert depth result to point cloud?

**Comment by VitorGuizilini-TRI** [comment]
You can project the 2D pixels to 3D using the predicted depth and camera intrinsics (you can use our camera class, it contains the .reconstruct() method that does that).
We are also working on a visualization tool that will soon be available, I will let you know once that is out!

**Comment by EmreOzkose** [comment]
@jinfagang there is a very basic Ros&Rviz implementation here: [3D-ros-visualization-of-depth-maps](https://github.com/EmreOzkose/3D-ros-visualization-of-depth-maps) with a clear and basic explanation. If you are a beginner, it may help you untill the official release for visualization.

**Comment by kwea123** [comment]
I used to use also ROS to visualize point cloud sequence which was both fast and easy-to-manipulate, but I find it somewhat inconvenient because of the need to install ROS (I change PC often so installation is quite tedious..), it would be great to have a python-only tool that can do it.

btw, @EmreOzkose there's an message type called [PointCloud2](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/PointCloud2.html) which is exactly for point cloud visualization, I think it's much faster than creating lots of point messages. My python script to render kitti pointcloud looks like [this](https://github.com/kwea123/ROS_notes/blob/master/kitti/kitti_pointcloud.py). Also your formula to convert uvdepth to xyz is totally wrong, it should involve the intrinsics and the correct formula is `xyz = K^-1(uv1)*d` in camera coordinate...

**Comment by davidalford** [comment]
Did anything every come of the visualization tool?
