### ISSUE TITLE
Error when "make docker-build"

### ISSUE THREAD

**Issue by oconnor127** [TRI-ML/packnet-sfm#136]
Hey,
I ran $ sudo make docker-build now on 2 different devices and get the same error at the end:
```
Skipping link: not a file: https://pypi.org/simple/pip/
Given no hashes to check 163 links for project 'pip': discarding no candidates
Removed build tracker: '/tmp/pip-req-tracker-ifcy0tou'
The command '/bin/bash -cu pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .' returned a non-zero code: 1
Makefile:65: recipe for target 'docker-build' failed
make: *** [docker-build] Error 1

```
Is that a common issue? Btw. there has been a lot of warnings during that building process. I followed the guidelines from https://docs.docker.com/engine/install/ubuntu/ to install docker. The OS is ubuntu 18 and 20. Looking forward for any advices :)

**Comment by surfii3z** [comment]
The same happens to me on Ubuntu `18.04 LTS, CUDA 11.0, Nvidia Driver 460.73.01, gcc 7.5.0`

**Comment by surfii3z** [comment]
Hi, I think I found the workaround for this situation.

> Yes, I am also getting the same issue when I use the latest commit. Reverting to the `e5f2f675de1c4e85e772065e550db55b13264265` commit solves.
_Originally posted by @ishitamed19 in https://github.com/NVIDIA/apex/issues/1090#issuecomment-826390918_


What you can do is to checkout `e5f2f675de1c4e85e772065e550db55b13264265` commit of apex by adding

`RUN git checkout e5f2f675de1c4e85e772065e550db55b13264265` AFTER this line

https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/docker/Dockerfile#L95

Hope this helps.

**Comment by tiassap** [comment]
@surfii3z  I did like you said but I still get the error, but this time a bit different.
`ERROR: Cannot install -r requirements.txt (line 2) and botocore==1.12.79 because these package versions have conflicting dependencies.`

In addition I also had a bunch of warnings like this in the middle:
`warning: integer conversion resulted in a change of sign`
as well as this in the beginning:
`Warning: Torch did not find available GPUs on this system`

(I am using Ubuntu 20.04 LTS and I believe I have installed NVIDIA driver and `nvidia-docker2` package correctly)

Please help

**Comment by surfii3z** [comment]
Hi @tiassap,

There is only one place in docker that deals with requirements.txt
https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/docker/Dockerfile#L126-L128

This issue is the well-known issue in dgp repo, please see
https://github.com/TRI-ML/dgp/issues/9#issue-775160678

My workaround was to clone the repo with the requirements.txt updated for bug fix. In my case, I replace this line
https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/docker/Dockerfile#L126

with
```bash
RUN git clone https://github.com/tlalexander/dgp.git \
```

Hope this helps

**Comment by tiassap** [comment]
Thanks @surfii3z 

With your suggestion I could initiate it but I still got this error:

> ConnectionResetError: [Errno 104] Connection reset by peer
> make: *** [Makefile:77: docker-run] Error 1

Did you encounter  this too?

**Comment by surfii3z** [comment]
I have never faced this kind of error. sorry.
