### ISSUE TITLE
how to genereate pesudo lidar ?

### ISSUE THREAD

**Issue by jinfagang** [TRI-ML/packnet-sfm#144]
how to genereate pesudo lidar ?

**Comment by VitorGuizilini-TRI** [comment]
You can use our camera class, it has a `reconstruct` method that takes a depth map and produces a pointcloud:

https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/packnet_sfm/geometry/camera.py#L112

**Comment by chapa17** [comment]
Hello @VitorGuizilini-TRI 

I am trying to reconstruct point cloud using `def recontruct()` function for KITTI_tiny dataset. But I am getting a scattered point cloud which somehow looks weird. Can you please guide me where I am wrong? 

Also I am confused with the camera calibration matrix since in the KITTI_tiny folder there are two calibration matrix values one in `calib_cam_to_cam.txt` and other is `cam.txt`. Can anyone please confirm which matrix I need to use for point cloud reconstruction? 

Thank you!!

**Comment by Alvin0629** [comment]
> Hello @VitorGuizilini-TRI
> 
> I am trying to reconstruct point cloud using `def recontruct()` function for KITTI_tiny dataset. But I am getting a scattered point cloud which somehow looks weird. Can you please guide me where I am wrong?
> 
> Also I am confused with the camera calibration matrix since in the KITTI_tiny folder there are two calibration matrix values one in `calib_cam_to_cam.txt` and other is `cam.txt`. Can anyone please confirm which matrix I need to use for point cloud reconstruction?
> 
> Thank you!!


Is it possible to share your reconstruction code? I am also getting a weird reconstruction result right now.
