### ISSUE TITLE
Did you compare packnet to resnet50 monodepth on kitti dataset?

### ISSUE THREAD

**Issue by aj96** [TRI-ML/packnet-sfm#24]
Hello,

Very great paper! In table 3 of your paper, you show that absolute relative error for monodepth2 resnet was 0.115. PackNet was 0.111. This doesn't seem like a very big difference? Was the monodepth2 resnet resnet18 or resnet50? If it was only resnet18, then I would suspect that resnet50 would close this small improvement in accuracy to an even smaller improvement over monodepth2. But on your DDAD dataset results, the difference between packnet and monodepth2 resnet18 and resnet50 is huge.

Can you please elaborate on this?

Thank you.

**Comment by VitorGuizilini-TRI** [comment]
We report ResNet50 results on the paper, for KITTI the biggest improvement comes from using high resolution images (monodepth2 barely reports any improvement from MR to HR). Also, KITTI is a small dataset that has been saturated, that's part of the reason for us to introduce DDAD, with longer depth ranges of up to 200m. We believe that's why the gap is larger (more validation images, higher resolution images, longer depth ranges, and an overall tougher dataset). 

Having said that, we welcome experimentation, we have already improved on the reported DDAD numbers internally, and hopefully someone will eventually beat us!
