### ISSUE TITLE
About using Ground Truth during the training, testing and Validation Process

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#61]
Are you converting Volodyne depth files ( .npz) files to PNG output as the ground truth in your program and use those ground truth files for the training or validation process? Cause I can see those converted ground truth files can be found in the KITTI_raw files. However, inside the KITTI_tiny dataset that you provided, there is no PNG files as the ground truth. I appreciate if you help me.

Thank you! :)

**Comment by VitorGuizilini-TRI** [comment]
KITTI has two different depth types: velodyne (raw LiDAR scans, saved as .npz) and groundtruth (accumulated and cleaned saved as .png). Since KITTI_raw is only for testing and overfitting purposes, we only provide velodyne depth maps, but they have the same role and just happen to be stored in different ways.
